const axios = require('axios');

const muslimUsers = [
  {
    email: "fatima.ahmed@example.com",
    password: "password123",
    name: "Fatima Ahmed",
    age: 24,
    educationLevel: "Master's",
    occupation: "Data Scientist",
    learningGoals: "Master deep learning and neural networks for healthcare applications",
    subjects: ["Deep Learning", "Python", "Healthcare AI"],
    learningStyle: "Visual",
    previousExperience: "Strong background in statistics and programming",
    strengths: "Analytical thinking, mathematical aptitude",
    weaknesses: "Limited cloud computing experience",
    specificChallenges: "Understanding transformer architectures",
    availableHoursPerWeek: 20,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "mohammed.hassan@example.com",
    password: "password123",
    name: "Mohammed Hassan",
    age: 30,
    educationLevel: "Bachelor's",
    occupation: "Software Engineer",
    learningGoals: "Learn cloud architecture and microservices",
    subjects: ["AWS", "Docker", "Kubernetes"],
    learningStyle: "Kinesthetic",
    previousExperience: "5 years in backend development",
    strengths: "Problem-solving, API design",
    weaknesses: "DevOps practices",
    specificChallenges: "Container orchestration",
    availableHoursPerWeek: 15,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "aisha.khan@example.com",
    password: "password123",
    name: "Aisha Khan",
    age: 22,
    educationLevel: "Bachelor's",
    occupation: "Junior Developer",
    learningGoals: "Master full-stack web development",
    subjects: ["React", "Node.js", "MongoDB"],
    learningStyle: "Visual",
    previousExperience: "Recent graduate, basic web development",
    strengths: "Quick learner, creative thinking",
    weaknesses: "Database design",
    specificChallenges: "State management in React",
    availableHoursPerWeek: 25,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "omar.ibrahim@example.com",
    password: "password123",
    name: "Omar Ibrahim",
    age: 35,
    educationLevel: "PhD",
    occupation: "Research Scientist",
    learningGoals: "Apply machine learning to climate research",
    subjects: ["Machine Learning", "Climate Science", "Python"],
    learningStyle: "Reading-Writing",
    previousExperience: "Expert in climate modeling",
    strengths: "Research methodology, data analysis",
    weaknesses: "Programming optimization",
    specificChallenges: "Large-scale data processing",
    availableHoursPerWeek: 10,
    learningPace: "Slow",
    motivationLevel: "Medium"
  },
  {
    email: "zainab.ali@example.com",
    password: "password123",
    name: "Zainab Ali",
    age: 27,
    educationLevel: "Master's",
    occupation: "UX Designer",
    learningGoals: "Learn frontend development and animation",
    subjects: ["JavaScript", "CSS", "Animation"],
    learningStyle: "Visual",
    previousExperience: "Strong design background, basic coding",
    strengths: "Design thinking, user empathy",
    weaknesses: "Complex JavaScript",
    specificChallenges: "Performance optimization",
    availableHoursPerWeek: 12,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "abdullah.malik@example.com",
    password: "password123",
    name: "Abdullah Malik",
    age: 29,
    educationLevel: "Bachelor's",
    occupation: "DevOps Engineer",
    learningGoals: "Master Kubernetes and infrastructure as code",
    subjects: ["Kubernetes", "Terraform", "CI/CD"],
    learningStyle: "Kinesthetic",
    previousExperience: "3 years in DevOps",
    strengths: "Automation, troubleshooting",
    weaknesses: "Security best practices",
    specificChallenges: "Multi-cloud deployments",
    availableHoursPerWeek: 18,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "mariam.yusuf@example.com",
    password: "password123",
    name: "Mariam Yusuf",
    age: 26,
    educationLevel: "Master's",
    occupation: "AI Researcher",
    learningGoals: "Research natural language processing for Arabic",
    subjects: ["NLP", "Transformers", "Arabic AI"],
    learningStyle: "Reading-Writing",
    previousExperience: "Strong ML background",
    strengths: "Research, multilingual expertise",
    weaknesses: "Production deployment",
    specificChallenges: "Low-resource language models",
    availableHoursPerWeek: 22,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "hamza.rahman@example.com",
    password: "password123",
    name: "Hamza Rahman",
    age: 31,
    educationLevel: "Bachelor's",
    occupation: "Mobile Developer",
    learningGoals: "Master Flutter and cross-platform development",
    subjects: ["Flutter", "Dart", "Mobile UI"],
    learningStyle: "Kinesthetic",
    previousExperience: "Native Android development",
    strengths: "UI implementation, performance",
    weaknesses: "iOS-specific features",
    specificChallenges: "State management patterns",
    availableHoursPerWeek: 16,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "khadija.omar@example.com",
    password: "password123",
    name: "Khadija Omar",
    age: 23,
    educationLevel: "Bachelor's",
    occupation: "Data Analyst",
    learningGoals: "Learn machine learning and predictive analytics",
    subjects: ["Machine Learning", "Statistics", "SQL"],
    learningStyle: "Visual",
    previousExperience: "Strong Excel and SQL skills",
    strengths: "Data visualization, statistics",
    weaknesses: "Programming fundamentals",
    specificChallenges: "Understanding ML algorithms",
    availableHoursPerWeek: 20,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "yusuf.ahmed@example.com",
    password: "password123",
    name: "Yusuf Ahmed",
    age: 28,
    educationLevel: "Master's",
    occupation: "Cybersecurity Analyst",
    learningGoals: "Master penetration testing and ethical hacking",
    subjects: ["Cybersecurity", "Networking", "Linux"],
    learningStyle: "Kinesthetic",
    previousExperience: "Network administration background",
    strengths: "Security awareness, networking",
    weaknesses: "Advanced cryptography",
    specificChallenges: "Exploit development",
    availableHoursPerWeek: 14,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "ayesha.siddiqui@example.com",
    password: "password123",
    name: "Ayesha Siddiqui",
    age: 25,
    educationLevel: "Bachelor's",
    occupation: "Product Manager",
    learningGoals: "Learn data analytics and product metrics",
    subjects: ["Data Analytics", "SQL", "Product Management"],
    learningStyle: "Visual",
    previousExperience: "Business background, basic analytics",
    strengths: "Communication, strategic thinking",
    weaknesses: "Technical implementation",
    specificChallenges: "A/B testing methodology",
    availableHoursPerWeek: 10,
    learningPace: "Slow",
    motivationLevel: "Medium"
  },
  {
    email: "bilal.khan@example.com",
    password: "password123",
    name: "Bilal Khan",
    age: 33,
    educationLevel: "PhD",
    occupation: "Machine Learning Engineer",
    learningGoals: "Research reinforcement learning applications",
    subjects: ["Reinforcement Learning", "Neural Networks", "Python"],
    learningStyle: "Reading-Writing",
    previousExperience: "Expert in supervised learning",
    strengths: "Algorithm design, mathematics",
    weaknesses: "Distributed computing",
    specificChallenges: "Training stability in RL",
    availableHoursPerWeek: 25,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "safiya.mohammad@example.com",
    password: "password123",
    name: "Safiya Mohammad",
    age: 24,
    educationLevel: "Bachelor's",
    occupation: "Frontend Developer",
    learningGoals: "Master React and modern frontend frameworks",
    subjects: ["React", "TypeScript", "Web Performance"],
    learningStyle: "Visual",
    previousExperience: "HTML/CSS/JavaScript basics",
    strengths: "UI implementation, accessibility",
    weaknesses: "Complex state management",
    specificChallenges: "Performance optimization",
    availableHoursPerWeek: 18,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "tariq.hussain@example.com",
    password: "password123",
    name: "Tariq Hussain",
    age: 36,
    educationLevel: "Master's",
    occupation: "Solutions Architect",
    learningGoals: "Learn cloud-native architecture patterns",
    subjects: ["Cloud Architecture", "Microservices", "AWS"],
    learningStyle: "Reading-Writing",
    previousExperience: "15 years in enterprise software",
    strengths: "System design, architecture",
    weaknesses: "Modern frontend frameworks",
    specificChallenges: "Serverless architecture",
    availableHoursPerWeek: 12,
    learningPace: "Medium",
    motivationLevel: "Medium"
  },
  {
    email: "amina.farah@example.com",
    password: "password123",
    name: "Amina Farah",
    age: 22,
    educationLevel: "Bachelor's",
    occupation: "Student",
    learningGoals: "Learn web development from scratch",
    subjects: ["HTML", "CSS", "JavaScript"],
    learningStyle: "Visual",
    previousExperience: "Complete beginner",
    strengths: "Motivated, creative",
    weaknesses: "No programming experience",
    specificChallenges: "Understanding programming logic",
    availableHoursPerWeek: 30,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "ibrahim.salam@example.com",
    password: "password123",
    name: "Ibrahim Salam",
    age: 32,
    educationLevel: "Master's",
    occupation: "Backend Developer",
    learningGoals: "Master distributed systems and scalability",
    subjects: ["Distributed Systems", "Redis", "Kafka"],
    learningStyle: "Kinesthetic",
    previousExperience: "Strong backend development",
    strengths: "API design, database optimization",
    weaknesses: "Message queues",
    specificChallenges: "Handling distributed transactions",
    availableHoursPerWeek: 15,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "hana.abdullah@example.com",
    password: "password123",
    name: "Hana Abdullah",
    age: 27,
    educationLevel: "Bachelor's",
    occupation: "QA Engineer",
    learningGoals: "Learn test automation and CI/CD",
    subjects: ["Selenium", "Testing", "CI/CD"],
    learningStyle: "Kinesthetic",
    previousExperience: "Manual testing background",
    strengths: "Attention to detail, testing",
    weaknesses: "Programming fundamentals",
    specificChallenges: "Writing maintainable test code",
    availableHoursPerWeek: 16,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "rashid.omar@example.com",
    password: "password123",
    name: "Rashid Omar",
    age: 29,
    educationLevel: "Master's",
    occupation: "Data Engineer",
    learningGoals: "Master big data processing and pipelines",
    subjects: ["Apache Spark", "Data Engineering", "Python"],
    learningStyle: "Reading-Writing",
    previousExperience: "Database administration",
    strengths: "SQL, data modeling",
    weaknesses: "Distributed computing",
    specificChallenges: "Real-time data processing",
    availableHoursPerWeek: 20,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "layla.mansoor@example.com",
    password: "password123",
    name: "Layla Mansoor",
    age: 26,
    educationLevel: "Bachelor's",
    occupation: "Business Analyst",
    learningGoals: "Learn Python for data analysis",
    subjects: ["Python", "Data Analysis", "Excel"],
    learningStyle: "Visual",
    previousExperience: "Business and Excel expert",
    strengths: "Business logic, requirements",
    weaknesses: "Programming concepts",
    specificChallenges: "Data manipulation with pandas",
    availableHoursPerWeek: 12,
    learningPace: "Slow",
    motivationLevel: "Medium"
  },
  {
    email: "mustafa.zahir@example.com",
    password: "password123",
    name: "Mustafa Zahir",
    age: 34,
    educationLevel: "PhD",
    occupation: "Computer Vision Researcher",
    learningGoals: "Research 3D computer vision and SLAM",
    subjects: ["Computer Vision", "3D Reconstruction", "Deep Learning"],
    learningStyle: "Reading-Writing",
    previousExperience: "Expert in 2D vision",
    strengths: "Research, mathematics",
    weaknesses: "Real-time processing",
    specificChallenges: "3D scene understanding",
    availableHoursPerWeek: 25,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "nadia.bashir@example.com",
    password: "password123",
    name: "Nadia Bashir",
    age: 23,
    educationLevel: "Bachelor's",
    occupation: "UI/UX Designer",
    learningGoals: "Learn prototyping and user research",
    subjects: ["Figma", "User Research", "Design Systems"],
    learningStyle: "Visual",
    previousExperience: "Graphic design background",
    strengths: "Visual design, creativity",
    weaknesses: "User research methods",
    specificChallenges: "Creating interactive prototypes",
    availableHoursPerWeek: 14,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "samir.karim@example.com",
    password: "password123",
    name: "Samir Karim",
    age: 31,
    educationLevel: "Master's",
    occupation: "Blockchain Developer",
    learningGoals: "Master smart contract development",
    subjects: ["Solidity", "Ethereum", "Web3"],
    learningStyle: "Kinesthetic",
    previousExperience: "Backend development",
    strengths: "Cryptography, distributed systems",
    weaknesses: "Smart contract security",
    specificChallenges: "Gas optimization",
    availableHoursPerWeek: 18,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "ruqaya.ahmed@example.com",
    password: "password123",
    name: "Ruqaya Ahmed",
    age: 25,
    educationLevel: "Bachelor's",
    occupation: "Technical Writer",
    learningGoals: "Learn API documentation and developer tools",
    subjects: ["API Documentation", "Technical Writing", "Markdown"],
    learningStyle: "Reading-Writing",
    previousExperience: "Content writing background",
    strengths: "Communication, clarity",
    weaknesses: "Technical depth",
    specificChallenges: "Understanding complex APIs",
    availableHoursPerWeek: 10,
    learningPace: "Slow",
    motivationLevel: "Medium"
  },
  {
    email: "faisal.noor@example.com",
    password: "password123",
    name: "Faisal Noor",
    age: 28,
    educationLevel: "Master's",
    occupation: "Game Developer",
    learningGoals: "Master Unity and game physics",
    subjects: ["Unity", "C#", "Game Design"],
    learningStyle: "Kinesthetic",
    previousExperience: "Indie game development",
    strengths: "Programming, creativity",
    weaknesses: "3D modeling",
    specificChallenges: "Multiplayer networking",
    availableHoursPerWeek: 22,
    learningPace: "Fast",
    motivationLevel: "High"
  },
  {
    email: "sumaya.hassan@example.com",
    password: "password123",
    name: "Sumaya Hassan",
    age: 30,
    educationLevel: "Bachelor's",
    occupation: "System Administrator",
    learningGoals: "Learn cloud migration and automation",
    subjects: ["Linux", "Ansible", "Cloud Migration"],
    learningStyle: "Kinesthetic",
    previousExperience: "10 years in IT",
    strengths: "System troubleshooting, networking",
    weaknesses: "Programming scripts",
    specificChallenges: "Infrastructure automation",
    availableHoursPerWeek: 12,
    learningPace: "Medium",
    motivationLevel: "Medium"
  },
  {
    email: "khalid.shareef@example.com",
    password: "password123",
    name: "Khalid Shareef",
    age: 27,
    educationLevel: "Master's",
    occupation: "IoT Engineer",
    learningGoals: "Build smart home automation systems",
    subjects: ["IoT", "Raspberry Pi", "MQTT"],
    learningStyle: "Kinesthetic",
    previousExperience: "Electronics background",
    strengths: "Hardware integration, sensors",
    weaknesses: "Cloud platforms",
    specificChallenges: "Edge computing",
    availableHoursPerWeek: 16,
    learningPace: "Medium",
    motivationLevel: "High"
  },
  {
    email: "hafsa.malik@example.com",
    password: "password123",
    name: "Hafsa Malik",
    age: 24,
    educationLevel: "Bachelor's",
    occupation: "Digital Marketing Specialist",
    learningGoals: "Learn marketing analytics and automation",
    subjects: ["Google Analytics", "SEO", "Marketing Automation"],
    learningStyle: "Visual",
    previousExperience: "Social media marketing",
    strengths: "Content strategy, creativity",
    weaknesses: "Data analysis",
    specificChallenges: "ROI measurement",
    availableHoursPerWeek: 10,
    learningPace: "Slow",
    motivationLevel: "Medium"
  },
  {
    email: "idris.yusuf@example.com",
    password: "password123",
    name: "Idris Yusuf",
    age: 35,
    educationLevel: "PhD",
    occupation: "Bioinformatics Researcher",
    learningGoals: "Apply ML to genomic data analysis",
    subjects: ["Bioinformatics", "Machine Learning", "Python"],
    learningStyle: "Reading-Writing",
    previousExperience: "Biology and statistics expert",
    strengths: "Domain knowledge, research",
    weaknesses: "Advanced ML techniques",
    specificChallenges: "Large-scale genomic analysis",
    availableHoursPerWeek: 20,
    learningPace: "Medium",
    motivationLevel: "High"
  }
];

async function createUsers() {
  let successCount = 0;
  let errorCount = 0;

  for (const user of muslimUsers) {
    try {
      const response = await axios.post('http://localhost:3000/api/auth/signup', user);
      console.log(`✅ Created: ${user.name} (${user.occupation})`);
      successCount++;
      await new Promise(resolve => setTimeout(resolve, 500));
    } catch (error) {
      const errorMsg = error.response ? error.response.data.error : error.message;
      console.error(`❌ Failed: ${user.name} - ${errorMsg}`);
      errorCount++;
    }
  }

  console.log(`\n📊 Summary: ${successCount} users created, ${errorCount} failed`);
}

createUsers();
